source 'https://rubygems.org'
gem 'crack'
gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'growl'
gem 'cane'
gem 'reek'
gem 'ruby_gntp'
gem 'simplecov', :require => false, :group => :test
gem 'fabrication'